default_platform(:ios)

platform :ios do
  desc "Build and upload the app"
  lane :build_and_upload do
    api_key = app_store_connect_api_key(
      key_id: "X22F658K7F",
      issuer_id: "69a6de77-92ab-47e3-e053-5b8c7c11a4d1",
      key_filepath: "../../AuthKey_X22F658K7F.p8"
    )
    build_app(
      scheme: "template StickerPackExtension"
    )
    upload_to_app_store(
      force: true,
      skip_metadata: true,
      skip_screenshots: true,
      precheck_include_in_app_purchases: false,
    )
  end
end